const data = {
    north_menu_odd: 
      {Sunday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Black Chana",
        "Mixed Paratha",
        "Curd",
        "Green Chutney & Sauce"],
        lunch:["Veg Biryani (Basmati)",
        "Phulka",
        "Dal Fry",
        "Mutter Paneer",
        "Icecream cup(1)/Corneto(3)",
        "Boondi Raita",
        "Fryums",
        "Mixed Salad",
        "Mixed Veg Pickle"],
        dinner:["Plain Rice",
        "Bhatura(1)/Methi Poori(3)",
        "Chole(1)/Aloo Dum(3)",
        "Masoor Dal",
        "Masala Papad",
        "Salad",
        "Mango Pickle",
        "Seasonal Fruit"],
      },
      Monday:{
        bf:[ "Brown & White Bread",
        "Mango Jam",
        "OatMeal (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Green Mong Sprouts",
        "Rava Khichdi (1)",
        "Semiyan Upma (3)",
        "Coconut Chutney"],
        lunch:["Plain Rice",
        "Phulka",
        "Dal Tadka",
        "Carrot Beans Dry",
        "Soyabean Chunk Curry",
        "Curd",
        "Papad",
        "Salad",
        "Lemon Pickle"],
        dinner:["Mixed Veg Fried Rice",
        "MethiChapati",
        "Manchurian",
        "Dal Fry",
        "Fryums",
        "Salad",
        "Mix Veg Pickle",
        "Banana"],
      },
      Tuesday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Peanut Sundal",
        "Poha +Lemon&Onion",
        "Jalebi",
        "Tamrind Chutney"],
        lunch:["Plain Rice",
        "Phulka",
        "Rajma",
        "Karela Bhujia Crispy",
        "Mixed Saag",
        "Lassi",
        "Fryums",
        "Salad",
        "Pickle"],
        dinner:["Plain Rice",
        "Phulka",
        "Aloo Bhindi Bhujiya",
        "Dal Makhani",
        "Papad",
        "Salad",
        "Pickle",
        "Pineapple Keshri (1) Kheer(3)"],     
      },
      Wednesday:{
        bf:["Brown & White Bread",
        "Strawberry Jam",
        "Oatmeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "White Bread Channa Chaat",
        "Mix Veg Uthappam",
        "Coconut Chutney",
        "Sambhar"],
        lunch:["Peas Pulao",
        "Chapati",
        "Dal Fry",
        "Aloo Soya Peas Dry",
        "Kadhai Paneer",
        "Curd",
        "Masala Papad",
        "Salad",
        "Mango Pickle"],
        dinner:["Plain Rice",
        "Mix Veg Paratha",
        "Green Chutney & Curd",
        "Rajma Masala",
        "Papad",
        "Salad",
        "Lemon Pickle",
        "WaterMelon"],  
      },
      Thursday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Black Chnana Sprout",
        "Daliya(1)/Macroni(3)",
        "Chutney(1)/Ketchup(3)"],
        lunch:["Plain Rice",
        "Phulka",
        "Green Moong Dal",
        "Red Pumpkin Chana",
        "Yum Dry",
        "Curd",
        "Fryums",
        "Mixed Salad",
        "Mixed Veg Pickle"],
        dinner:["Ghee Rice (Basmati)",
        "Phulka",
        "Moong Dal",
        "Mix Veg Dry",
        "Fryums",
        "Salad",
        "Mix Veg Pickle",
        "Moong Dal Halwa(1)",
        "Parapu Payasam(3)"],     
      },
      Friday:{
        bf:["Brown & White Bread",
        "Mango Jam",
        "Oatmeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Moong Sprouts",
        "Idly + Vada",
        "Coconut Chutney",
        "Sambhar"],
        lunch:["Plain Rice",
        "Phulka",
        "Dal Tadka",
        "Snake Guard Chana Dry",
        "Palak Paneer",
        "Curd",
        "Papad",
        "Salad",
        "Lemon Pickle"],
        dinner:["Plain Rice",
        "Phulka",
        "Raw Banana Karamani",
        "Dal Fry",
        "Masala Papad",
        "Salad",
        "Mango Pickle",
        "Seasonal Fruit"],
      },
      Saturday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Mixed Sprouts",
        "Plain Dosa",
        "Aloo Masala",
        "Sambhar & Chutney"],
        lunch:["Plain Rice",
        "Chapati",
        "Dal Makhani",
        "Cabbage Mutter Dry",
        "Bhindi Do Pyaza",
        "Curd",
        "Papad",
        "Salad",
        "Mango Pickle"],
        dinner:["Plain Rice",
        "Phulka",
        "Tava Mix Veg Dry",
        "Palak Dal",
        "Papad",
        "Lemon Pickle",
        "Banana",
        "Bournvita Milk"],
      }
    },
    north_menu_even :
      {Sunday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Black Chana Sprouts",
        "Aloo Paratha",
        "Curd",
        "Green Chutney & Sauce"],
        lunch:["Kashmiri Pulao (Basmati)",
        "Phulka",
        "Dal Fry",
        "Paneer Butter Masala",
        "Gulab Jamun",
        "Mixed Veg Raita",
        "Fryums",
        "Mixed Salad",
        "Mixed Veg Pickle"],
        dinner:["Plain Rice",
        "Chapati",
        "Green Moong Dal",
        "Bhindi Fry",
        "Masala Papad",
        "Salad",
        "Mango Pickle",
        "Seasonal Fruit"],
      },
      Monday:{
        bf:[ "Brown & White Bread",
        "Mango Jam",
        "OatMeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Green Mong Sprouts",
        "Moong Dal Cheela",
        "Tomato Chutney"],
        lunch:["Plain Rice",
        "Phulka",
        "Palak Dal",
        "Tindly Fry",
        "Soya chunks Curry",
        "Curd",
        "Papad",
        "Salad",
        "Lemon Pickle"],
        dinner:["Plain Rice",
        "Phulka",
        "Dal Tadka",
        "Mix Veg Phuket",
        "Fryums",
        "Salad",
        "Mix Veg Pickle",
        "Banana"],
      },
      Tuesday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Peanut Sundal",
        "Poha +Lemon&Onion",
        "Jalebi",
        "Tamrind Chutney"],
        lunch:["Plain Rice",
        "Phulka",
        "Dal Makhani",
        "Lauki Chana Dal",
        "Aloo Saag Dry",
        "Lassi",
        "Fryums",
        "Salad",
        "Pickle"],
        dinner:["Plain Rice",
        "Phulka",
        "Mixed Dal",
        "Mutter Paneer",
        "Papad",
        "Salad",
        "Pickle",
        "Semiya Halwa(2)",
        "Sabudana Kheer(4)"],     
      },
      Wednesday:{
        bf:["Brown & White Bread",
        "Strawberry Jam",
        "Oatmeal (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "White Channa Chaat",
        "Maggi Dry",
        "Tomato Ketchup"],
        lunch:["Peas Pulao",
        "Chapati",
        "Dal Panchranga",
        "Jeera Allo(2) Aloo Mutter Dry(4)",
        "Palak Paneer",
        "Curd",
        "Masala Papad",
        "Salad",
        "Mango Pickle"],
        dinner:["Plain Rice",
        "Aloo Paratha",
        "Green Chutney & Curd",
        "Rajma Masala",
        "Papad",
        "Salad",
        "Lemon Pickle",
        "Seasonal Fruit"],  
      },
      Thursday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Black Chnana Sprout",
        "Pav Bhaji",
        "Lemon & Onion"],
        lunch:["Plain Rice",
        "Phulka",
        "Mixed Dal",
        "Bhindi Do Pyaza",
        "Carrot Beans Dry",
        "Curd",
        "Fryums",
        "Mixed Salad",
        "Mixed Veg Pickle"],
        dinner:["Ghee Rice (Basmati)",
        "Phulka",
        "Moong Dal",
        "Mix Veg Kolhapuri",
        "Fryums",
        "Salad",
        "Mix Veg Pickle",
        "Papaya"],     
      },
      Friday:{
        bf:["Brown & White Bread",
        "Mango Jam",
        "Oatmeal (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Moong Sprouts",
        "Kachori(2) Semiya Upma(4)",
        "Aloo Sabji & Tamrin Chutney(2)",
        "Coconut Chutney(4)"],
        lunch:[ "Plain Rice",
        "Phulka",
        "Moong Dal",
        "Mixed Sag+Badi", 
        "Aloo Muttor Curry",
        "Curd",
        "Papad",
        "Salad",
        "Lemon Pickle"],
        dinner:["Plain Rice",
        "Phulka",
        "Raw Banana Karamani",
        "Dal Fry",
        "Masala Papad",
        "Salad",
        "Mango Pickle",
        "WaterMelon"],
      },
      Saturday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Mixed Sprouts",
        "Poori",
        "Chole"],
        lunch:["Moong Dal Khichdi",
        "Chapati",
        "Aloo Chokha (Musturd Oil)",
        "Red Pumpkin black Chana",
        "Curd",
        "Papad",
        "Salad",
        "Mango Pickle"],
        dinner:["Jeera Rice",
        "Chapati",
        "Tava Mix Veg Dry",
        "Dal Makhani",
        "Papad",
        "Salad",
        "Lemon Pickle",
        "Banana",
        "Boost Milk"],
      }
    },
    south_menu_odd:
      {Sunday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Black Chana Sprouts",
        "Masala Dosa(1)",
        "Idiyappam(3)",
        "Coconut Chutney(1)Milk(3)",
        "Sambhar(1)Veg Kurma(3)"],
        lunch:["Veg Biryani (Basmati)",
        "Phulka",
        "Kadai Paneer",
        "Gulab Jamun(1)",
        "Cornetto(3)",
        "Onion Raita",
        "Fryums",
        "Mixed Salad",
        "Mixed Veg Pickle"],
        dinner:[ "Plain Rice",
        "Chapathi",
        "Clustered Beans Moongdal Kottu",
        "Raw Banana Karamani",
        "Masala Papad",
        "Salad",
        "Tomato Rasam",
        "Veg soup(1)",
        "Lemon Juice(3)",
        "Mango Pickle",
        "Seasonal Fruit"],
      },
      Monday:{
        bf:["Brown & White Bread",
        "Mango Jam",
        "OatMeal (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Green Mong Sprouts",
        "Idly+Vada",
        "Coconut Chutney(1)",
        "Groundnut(3)",
        "Sambhar"],
        lunch:[  "Plain Rice",
        "Methi Chapati",
        "Rajma Masala",
        "Sambhar",
        "Brinjal Mochhe",
        "Curd",
        "Papad",
        "Garlic Rasam",
        "Salad",
        "Gongroo Thoviyal",
        "Lemon Pickle"],
        dinner:["Plain Rice",
        "Aloo(1) Gobi(3) Paratha",
        "Green Peas Masala",
        "Curd+Green Chutney",
        "Papad",
        "Salad",
        "Lemon Water",
        "Thoviyal",
        "Carrot Halwa(1)",
        "Sabudana Kheer(3)"],
      },
      Tuesday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Peanut Sundal",
        "Puttu+Kadala Curry(1)",
        "Mysore Bonda(3)",
        "Rava Khichdi(1)",
        "Wheat Kichidi(3)",
        "Groundnut Chutney"],
        lunch:["Plain Rice",
        "Phulka",
        "Goungra Pappu",
        "Puli Kuzhambu",
        "Bitter Guard Fry",
        "Curd",
        "Fryums",
        "Lemon Rasam",
        "Salad",
        "Mint Thoviyal",
        "Corriender Chutney"],
        dinner:["Tomato Rice(1)",
        "Pudina Rice(3)",
        "Curd Rice",
        "Vatthal",
        "Salad",
        "Lemon Juice",
        "Buttermilk",
        "Mix Veg Pickle",
        "Banana"
        ],     
      },
      Wednesday:{
        bf:["Brown & White Bread",
        "Strawberry Jam",
        "Oatmeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "White Channa Chaat",
        "Onion Uthappam",
        "Coconut Chutney",
        "Sambhar"],
        lunch:["Plain Rice",
        "Pudina Chapati",
        "Carrot Beans Poriyal",
        "Sambhar",
        "Aloo Capsicum greavy",
        "Curd",
        "Vatthal",
        "Tomato Rasam",
        "Salad",
        "Ridge Guard Thoviyal",
        "Mango Pickle"],
        dinner:["Plain Rice",
        "Ragi(1)Wheat(3) Dosa",
        "Sambhar+Garlic Chutney",
        "Aloo Jeera",
        "Fryums",
        "Salad",
        "Tomato Rasam",
        "Lemon Water",
        "Mix Veg Pickle",
        "Papaya"],     
      },
      Thursday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Black Chnana Sprout",
        "Pesarattu+ Rava Upma",
        "Ginger Chutney",
        "Sambhar"],
        lunch:["Plain Rice",
        "Phulka",
        "Tomato Dal",
        "Avial",
        "Gobi65(1)",
        "Bhindi Aloo Fry(3)",
        "Curd",
        "Fryums",
        "Pepper Rasam",
        "Mixed Salad",
        "Curry Leave Thoviyal",
        "Mixed Veg Pickle"],
        dinner:["Veg Fried Rice",
        "Pulkha",
        "Dal Fry",
        "Gobi Manchurian",
        "Papad",
        "Salad",
        "Garlic Rasam",
        "ButterMilk",
        "Lemon Pickle",
        "Musk Melon(2)",
        "Watermelon(4)"],  
      },
      Friday:{
        bf:["Brown & White Bread",
        "Mango Jam",
        "Oatmeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Moong Sprouts",
        "Pongal Vada",
        "Coconut",
        "Chutney + Sambhar"],
        lunch:["Plain Rice",
        "Plain Chapati",
        "Masala Paneer",
        "Beetroot Poriyal",
        "Curd",
        "Papad",
        "Tomato Rasam",
        "Salad",
        "Gongro Thoviyal",
        "Lemon Pickle"],
        dinner:["Plain Rice",
        "Mix Veg Uthappam",
        "Sambhar",
        "Groundnut Chutney",
        "Aloo gobi mutter",
        "Masala Papad",
        "Salad",
        "Pepper Rasam",
        "ButterMilk",
        "Mango Pickle",
        "Mixed Fruit Salad"],
      },
      Saturday:{
        bf:[ "Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Mixed Sprouts",
        "Poori", 
        "Aloo Masala"],
        lunch:["Plain Rice",
        "Phulka",
        "Bottle Guard Kottu",
        "Sambhar",
        "Kerai Vada",
        "Curd",
        "Papad",
        "Lemon Rasam",
        "Salad",
        "Mint Thoviyal",
        "Chutney"],
        dinner:[ "Bisibella Bhat",
        "Puliogera(1) Rice",
        "Goungra(4) Rice",
        "Curd Rice",
        "Potato Chips",
        "Salad",
        "Bournvita Milk",
        "Lemon Pickle",
        "Banana"],
      }
    },
    south_menu_even:
      {Sunday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "BOiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Black Chana Sprouts",
        "Semiya Upma(2)",
        "Pongal(4)", 
        "Coconut Chutney",
        "Sambhar"],
        lunch:["Veg Biryani (Basmati)",
        "Phulka",
        "Dal Fry",
        "Paneer Butter Masala",
        "Custard bread(2)",
        "Parapu Paysam(4)",
        "Mixed Veg Raita",
        "Fryums",
        "Mixed Salad",
        "Mixed Veg Pickle"],
        dinner:["Plain Rice",
        "Bhature",
        "Chole",
        "Sambhar",
        "Masala Papad",
        "Salad",
        "Tomato Rasam",
        "Lemon Juice(2)",
        "Veg Soup(4)",
        "Mango Pickle",
        "Seasonal Fruit"],
      },
      Monday:{
        bf:["Brown & White Bread",
        "Mango Jam",
        "OatMeal (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Green Mong Sprouts",
        "Rava Idly+Vada",
        "Coconut Chutney(4)",
        "Groundnut(2)",
        "Sambhar"],
        lunch:["Plain Rice",
        "Methi Chapati",
        "Palak Pappu",
        "Sambhar",
        "Bhindi Dry",
        "Curd",
        "Papad",
        "Garlic Rasam",
        "Salad",
        "Gongroo Thoviyal",
        "Lemon Pickle"],
        dinner:[ "Plain Rice",
        "Phulka",
        "Veg Kurma",
        "Sambhar",
        "Vatthal",
        "Salad",
        "Lemon Rasam",
        "ButterMilk",
        "Mix Veg Pickle",
        "Banana"],
      },
      Tuesday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Peanut Sundal",
        "Kal Dosa",
        "Pudina Chutney",
        "Vada Curry"],
        lunch:["Plain Rice",
        "Phulka",
        "Yam Kara Kuzhambu",
        "Aloo dum",
        "Carrot Beans Poriyal",
        "Curd",
        "Fryums",
        "Lemon Rasam",
        "Salad",
        "Mint Thoviyal",
        "Corriender Chutney"],
        dinner:["Jeera Rice (Basmati)",
        "Chapati",
        "Dal Fry",
        "Mutter Paneer",
        "Papad",
        "Salad",
        "Lemon Water",
        "Thoviyal",
        "Pineapple keshari(2)",
        "Sweet Pongal(4)"],     
      },
      Wednesday:{
        bf:["Brown & White Bread",
        "Strawberry Jam",
        "Oatmeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "White Channa Chaat",
        "Maggi Dry",
        "Tomato Ketchup",
        "Ragi Koozh"],
        lunch:["Plain Rice",
        "PudinaChapati",
        "Gongroo Dal",
        "Sambhar",
        "Tindly Fry",
        "Curd",
        "Vatthal",
        "Tomato Rasam",
        "Salad",
        "Ridge Guard Thoviyal",
        "Mango Pickle"],
        dinner:["Plain Rice",
        "Idly(2)",
        "Plain Dosa(4)",
        "Coconut Chutney",
        "Sambhar+Podi&Oil",
        "Papad",
        "Salad",
        "Garlic Rasam",
        "ButterMilk",
        "Lemon Pickle",
        "Pineapple(1)",
        "Watermelon(3)"],  
      },
      Thursday:{
        bf:["Brown & White Bread",
        "Pineapple Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Black Chnana Sprout",
        "Pongal+Vada(2) Pasta(4)",
        "Groundnut Chutney(2)",
        "Ketchup(4)",
        "Sambhar"],
        lunch:["Plain Rice",
        "Phulka",
        "Mixed Dal",
        "Moru Kuzhambu",
        "Aloo kara Poriyal",
        "Curd",
        "Fryums",
        "Pepper Rasam",
        "Mixed Salad",
        "Curry Leave Thoviyal",
        "Mixed Veg Pickle"],
        dinner:["Kichidi",
        "Chapati",
        "Crispy Veg(No Potato)",
        "Sambhar",
        "Fryums",
        "Salad",
        "Tomato Rasam",
        "Lemon Water",
        "Lemon Pickle(2)",
        "Mango Pickle(4)",
        "Papaya"],     
      },
      Friday:{
        bf:["Brown & White Bread",
        "Mango Jam",
        "Oatmeal (Veg)",
        "Boiled Egg (Non-Veg)",
        "Tea/Coffee/Milk",
        "Boiled Moong Sprouts",
        "Poori",
        "Aloo Masala"],
        lunch:["Plain Rice",
        "PlainChapati",
        "Palak Paneer",
        "Sambhar",
        "Beetroot Poriyal(2)",
        "Red pumpkin karamani(4)",
        "Curd",
        "Papad",
        "Tomato Rasam",
        "Salad",
        "Gongro Thoviyal",
        "Lemon Pickle"],
        dinner:["Plain Rice",
        "Millet Dosa(2)",
        "Kerala Parota(4)",
        "Onion Chutney(2)",
        "Veg Kurma(4)",
        "Sambhar(2)",
        "Carrot Poriyal(4)",
        "Masala Papad",
        "Salad",
        "Pepper Rasam",
        "ButterMilk",
        "Mango Pickle",
        "Mixed Fruit Salad"],
      },
      Saturday:{
        bf:["Brown & White Bread",
        "Mixed fruit Jam",
        "Corn flakes (Veg)",
        "Omlet (Non-Veg)",
        "Tea/Coffee/Milk",
        "Mixed Sprouts",
        "Rava Dosa",
        "Kara Chutney",
        "Sambhar"],
        lunch:[ "Plain Rice",
        "Phulka",
        "Tomato Dal",
        "Sambhar",
        "Aloo Beans Poriyal",
        "Curd",
        "Papad",
        "Lemon Rasam",
        "Salad",
        "Mint Thoviyal",
        "Chutney"],
        dinner:["Sambhar Rice",
        "Tomato Rice(2)",
        "Coconut Rice(4)",
        "Curd Rice",
        "Potato Chips",
        "Salad",
        "Boost Milk",
        "Lemon Pickle",
        "Banana"],
      }
    },
};

export default data;
  